name: Build
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node 16
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: 'npm'

      - name: Install deps (legacy peer deps)
        run: npm install --legacy-peer-deps
        env:
          NPM_CONFIG_LEGACY_PEER_DEPS: "true"

      - name: Build project
        run: npm run build
        #env:
          #NODE_OPTIONS: --openssl-legacy-provider
